version: '3'
networks:
    custom-metrics-monitoring:

services:
    prometheus:
        image: prom/prometheus:v2.20.1
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./targets.json:/etc/prometheus/targets.json
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - "9090:9090"
        networks:
            - custom-metrics-monitoring
    
    grafana:
        image: grafana/grafana:7.1.3
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        networks:
            - custom-metrics-monitoring
    
    custom-metrics:
        build: .
        image: get-of-metrics:latest
        container_name: custom-metrics
        volumes:
            - ./connection-parameters.json:/get-of-metrics/connection-parameters.json
            - ./logs:/get-of-metrics/logs
        ports: 
            - "8000:8000"
        networks:
            - custom-metrics-monitoring