{
 "title": "sample-Test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(rx_bytes{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(tx_bytes{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(rx_packets{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(tx_packets{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(rx_drops{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(tx_drops{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(rx_errors{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(tx_errors{instance=\"localhost:9100\", job=\"node_exporter_metrics\", node_name=\"sample\"}[5m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  }
 ]
}