apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-svc-leaf-1
  namespace: get-of-metrics
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: scrape-metrics    
