{
 "title": "Leaf Spine Metrics Overall (Bandwidths)",
 "tags": [ "overall" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Leaf-1 Total Bandwitdh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name)(irate(rx_bytes_total{node_name=\"Leaf-1\"}[5m])*8)",
     "legendFormat": "recv {{node_name}}"
    },
    {
     "expr": "sum by (node_name)(irate(tx_bytes_total{node_name=\"Leaf-1\"}[5m])*8)",
     "legendFormat": "trans {{node_name}}"
    }
   ]
  },
  {
   "title": "Leaf-2 Total Bandwitdh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name)(irate(rx_bytes_total{node_name=\"Leaf-2\"}[5m])*8)",
     "legendFormat": "recv {{nodename}}"
    },
    {
     "expr": "sum by (node_name)(irate(tx_bytes_total{node_name=\"Leaf-2\"}[5m])*8)",
     "legendFormat": "trans {{nodename}}"
    }
   ]
  },
  {
   "title": "Spine-1 Total Bandwitdh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name)(irate(rx_bytes_total{node_name=\"Spine-1\"}[5m])*8)",
     "legendFormat": "recv {{node_name}}"
    },
    {
     "expr": "sum by (node_name)(irate(tx_bytes_total{node_name=\"Spine-1\"}[5m])*8)",
     "legendFormat": "trans {{node_name}}"
    }
   ]
  },
  {
   "title": "Spine-2 Total Bandwitdh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name)(irate(rx_bytes_total{node_name=\"Spine-2\"}[5m])*8)",
     "legendFormat": "recv {{nodename}}"
    },
    {
     "expr": "sum by (node_name)(irate(tx_bytes_total{node_name=\"Spine-2\"}[5m])*8)",
     "legendFormat": "trans {{nodename}}"
    }
   ]
  }
 ]
}