{
 "title": "Leaf Spine Metrics Per Port (Cumulative) - v2",
 "tags": [ "port-based" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_name", "query": "label_values(node_name)" },
   {
    "name": "port",
    "query": "label_values(rx_bytes_total{node_name=\"$node_name\"},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Receive Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_bytes_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tx_bytes_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_packets_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tx_packets_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_errors_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tx_errors_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Drops",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_drops_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Drops",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tx_drops_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Frame Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_frame_err_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Overrun Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_over_err_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "collisions_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive CRC Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rx_crc_err_total{node_name=\"$node_name\", device=~\"$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}